### ISSUE TITLE
Data points for ScanTool.net OBDLink SX

### ISSUE THREAD

**Issue by noloader** [Ircama/ELM327-emulator#17]
Hi Everyone/lrcama,

I wanted to add a few data points for ScanTool.net's OBDLink SX. It is different than the ELM327's. OBDLink uses an STM11xx and STM21xx, and not ELM327 chips. You can find them on Amazon at https://www.amazon.com/gp/product/B005ZWM0R4. The Amazon device uses a STM11xx.

The OBDLink is supposed to be ELM327 compatible, but it has some differences. We need to connect at 112500 8N1, and not 38400 8N1. Using 38400 8N1 will cause a hang with this device.

The version string for the STM11xx is `ELM327 v1.4b`. I don't know what the version string is for the STM21xx. Here's what an ATZ command and response looks like. Notice the leading `00 00 00 00`.

```
Command:
ATZ (reset)

Hex dump:
00 00 00 00 0d 0d 45 4c 4d 33 32 37 20 76 31 2e
34 62 0d 0d 3e

ASCII dump:


ELM327 v1.4b

>
```

So far the rest of the commands and responses look like the ELM327.

Feel free to close the report. I wanted to offer the data points since the OBDLink is supposed to be ELM327 compatible.

**Comment by Ircama** [comment]
Thanks @noloader for notifying an issue when the `hexheader` parameter includes null chars (zeroes) and CR chars.

The fix is in the [slave_raw](https://github.com/Ircama/ELM327-emulator/tree/slave_raw) branch, for testing.

The commands to configure this ScanTool.net OBDLink SX message are:

```
version hexheader 00 00 00 00 0d 0d
version ELM327 v1.4b
```

Please check after `python3 -m pip install --upgrade git+https://github.com/ircama/ELM327-emulator.git@slave_raw`
